#logging:
#  level:
#    org: DEBUG
#    com: DEBUG
jwt:
  secret:
    access: LejjnLZua6SlR7eZXByD2+9M5P+dYxK3IlfA6XgPksuXijiXMAcpulI03o2Vq+PjYENhgTJGXLNm7YS4f1+IMw==
    refresh: cRO8f7Q/HaE/X1QjxAHYL8Dm5qkTI68WiNi9elE1NFqsL2up0RlZn/e7aD2R5i8cMvCksBEDhUAOZAhsypQaXw==
spring:
  profiles:
    active: prod
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  security:
    enable: true # Ваша конфигурация безопасности
server:
  port: 9000

---
# Настройки для профиля local
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
#      data-locations: classpath:data-h2.sql
#      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none # Этот параметр указывает Hibernate не выполнять автоматическую генерацию DDL-скриптов

# Налаштування для профілю prod
---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: always
      data-locations: classpath:data-mysql.sql
      schema-locations: classpath:schema-mysql.sql
  datasource:
    url: jdbc:mysql://localhost:3306/bankproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none